#!/bin/bash

echo "=========================================="
echo "阿里云服务器连接 - 最终解决方案"
echo "=========================================="
echo ""

echo "当前状况:"
echo "  ✓ 网络正常 (百度可访问)"
echo "  ✓ VPN 已断开"
echo "  ✓ 密钥文件正确"
echo "  ✓ 服务器端口 22 已开放"
echo "  ✗ SSH 连接超时"
echo "  ✗ 手机热点可能屏蔽 22 端口"
echo ""

echo "=========================================="
echo "唯一可行的解决方案"
echo "=========================================="
echo ""

echo "【方案】使用阿里云控制台 VNC 连接"
echo "----------------------------------------"
echo "步骤:"
echo ""
echo "1. 手机/电脑浏览器访问:"
echo "   https://swas.console.aliyun.com"
echo ""
echo "2. 登录阿里云账号"
echo ""
echo "3. 找到你的轻量服务器 (Ubuntu-usvn)"
echo ""
echo "4. 点击 '远程连接' 按钮"
echo ""
echo "5. 选择 'VNC 远程连接'"
echo "   (不是 SSH 连接!)"
echo ""
echo "6. 输入用户名和密码:"
echo "   - 用户名: ubuntu (或 root)"
echo "   - 密码: 你创建服务器时设置的密码"
echo ""
echo "7. 如果忘记密码:"
echo "   - 在控制台点击 '重置密码'"
echo "   - 设置新密码后重启服务器"
echo "   - 再用新密码登录"
echo ""
echo "=========================================="
echo "登录后建议操作"
echo "=========================================="
echo ""
echo "1. 检查 SSH 服务状态:"
echo "   sudo systemctl status sshd"
echo ""
echo "2. 修改 SSH 端口 (避开运营商屏蔽):"
echo "   sudo nano /etc/ssh/sshd_config"
echo "   # 找到 Port 22，改为 Port 443"
echo "   sudo systemctl restart sshd"
echo ""
echo "3. 或者安装 Web 控制台 (如 Cockpit):"
echo "   sudo apt update"
echo "   sudo apt install cockpit"
echo "   # 然后通过 https://服务器IP:9090 管理"
echo ""
echo "=========================================="
echo "其他备选方案"
echo "=========================================="
echo ""
echo "方案 A: 切换到 WiFi 网络"
echo "   - 连接普通 WiFi 后再试 SSH"
echo "   - 大多数 WiFi 不会屏蔽 22 端口"
echo ""
echo "方案 B: 使用阿里云 App"
echo "   - 下载 '阿里云' App"
echo "   - 在手机上管理服务器"
echo "   - 支持 VNC 远程连接"
echo ""
echo "方案 C: 更换运营商"
echo "   - 某些运营商会屏蔽 22 端口"
echo "   - 尝试其他运营商的手机卡"
echo ""
echo "=========================================="
echo ""
echo "推荐: 立即使用 VNC 连接登录服务器"
echo "链接: https://swas.console.aliyun.com"
echo ""
echo "=========================================="
