#!/bin/bash

echo "=========================================="
echo "SSH 连接问题最终解决方案"
echo "=========================================="
echo ""

echo "当前问题:"
echo "  - SSH 端口已改为 443"
echo "  - 但连接仍然超时"
echo "  - 可能是防火墙或安全组未开放 443"
echo ""

echo "=========================================="
echo "步骤 1: 在服务器上检查端口监听"
echo "=========================================="
echo ""
echo "通过 VNC 登录后执行:"
echo ""
echo "1. 检查 SSH 是否在监听 443:"
echo "   sudo netstat -tlnp | grep :443"
echo "   或"
echo "   sudo ss -tlnp | grep :443"
echo ""
echo "2. 如果看到 sshd 在监听 0.0.0.0:443，说明配置正确"
echo "   如果没有，检查配置文件:"
echo "   cat /etc/ssh/sshd_config | grep Port"
echo ""

echo "=========================================="
echo "步骤 2: 开放防火墙端口"
echo "=========================================="
echo ""
echo "在服务器上执行:"
echo ""
echo "1. 检查防火墙状态:"
echo "   sudo ufw status"
echo ""
echo "2. 开放 443 端口:"
echo "   sudo ufw allow 443/tcp"
echo "   sudo ufw reload"
echo ""
echo "3. 如果使用 iptables:"
echo "   sudo iptables -A INPUT -p tcp --dport 443 -j ACCEPT"
echo "   sudo iptables-save"
echo ""

echo "=========================================="
echo "步骤 3: 配置阿里云防火墙"
echo "=========================================="
echo ""
echo "1. 登录 https://swas.console.aliyun.com"
echo "2. 找到服务器 → 安全 → 防火墙"
echo "3. 添加规则:"
echo "   - 协议: TCP"
echo "   - 端口: 443"
echo "   - 源地址: 0.0.0.0/0"
echo "4. 保存规则"
echo ""

echo "=========================================="
echo "步骤 4: 测试连接"
echo "=========================================="
echo ""
echo "配置完成后，在本地测试:"
echo ""
echo "   ssh -p 443 -i \"/Users/huangya/Documents/阿里云密钥对.pem\" root@47.83.173.6"
echo ""
echo "如果成功，更新 SSH 配置:"
echo ""
echo "   Host aliyun-swas"
echo "       HostName 47.83.173.6"
echo "       User root"
echo "       Port 443"
echo "       IdentityFile ~/Documents/阿里云密钥对.pem"
echo ""

echo "=========================================="
echo "快速命令参考"
echo "=========================================="
echo ""
echo "本地测试命令:"
echo "   ssh -p 443 -i \"/Users/huangya/Documents/阿里云密钥对.pem\" root@47.83.173.6"
echo ""
echo "服务器上检查命令:"
echo "   sudo netstat -tlnp | grep ssh"
echo "   sudo ufw status"
echo "   sudo iptables -L -n | grep 443"
echo ""
echo "=========================================="
