#!/bin/bash

echo "=========================================="
echo "阿里云轻量应用服务器 (SWAS) 连接诊断"
echo "=========================================="
echo ""

SERVER_IP="47.83.173.6"
KEY_FILE="/Users/huangya/Documents/阿里云密钥对.pem"

echo "服务器: $SERVER_IP"
echo "状态: 运行中 (用户确认)"
echo ""

echo "=========================================="
echo "常见原因和解决方案"
echo "=========================================="
echo ""

echo "【原因 1】防火墙/安全组未放行"
echo "  轻量服务器有独立的防火墙规则："
echo "  1. 登录 https://swas.console.aliyun.com"
echo "  2. 找到你的服务器"
echo "  3. 点击 '安全' 或 '防火墙' 标签"
echo "  4. 添加规则："
echo "     - 协议: TCP"
echo "     - 端口: 22"
echo "     - 源地址: 0.0.0.0/0 (或你的公网IP)"
echo ""

echo "【原因 2】SSH 服务未启动"
echo "  通过阿里云控制台 VNC 登录检查："
echo "  1. 在轻量服务器控制台点击 '远程连接'"
echo "  2. 选择 'VNC 远程连接'"
echo "  3. 登录后执行: sudo systemctl status ssh"
echo "  4. 如果未运行: sudo systemctl start ssh"
echo ""

echo "【原因 3】密钥权限问题"
echo "  阿里云密钥对需要特定权限："
echo "  1. 在控制台重置密钥对"
echo "  2. 或绑定新的密钥对"
echo "  3. 注意：重置密钥需要重启服务器"
echo ""

echo "【原因 4】IP 被防火墙拦截"
echo "  检查服务器是否启用了 fail2ban 等："
echo "  通过 VNC 登录后检查:"
echo "  sudo iptables -L | grep DROP"
echo "  sudo fail2ban-client status"
echo ""

echo "=========================================="
echo "快速解决步骤"
echo "=========================================="
echo ""
echo "步骤 1: 检查防火墙规则"
echo "  → 登录 https://swas.console.aliyun.com"
echo "  → 安全 → 防火墙 → 添加 22 端口规则"
echo ""
echo "步骤 2: 使用 VNC 登录检查"
echo "  → 控制台 → 远程连接 → VNC 远程连接"
echo "  → 用户名: ubuntu (Ubuntu系统) 或 root (CentOS)"
echo "  → 密码: 你在创建时设置的密码"
echo ""
echo "步骤 3: 检查 SSH 服务"
echo "  $ sudo systemctl status sshd"
echo "  $ sudo systemctl restart sshd"
echo ""
echo "步骤 4: 检查安全组"
echo "  $ sudo iptables -L -n | grep 22"
echo ""
echo "=========================================="
echo "手动连接命令"
echo "=========================================="
echo ""
echo "标准连接:"
echo "  ssh -i \"$KEY_FILE\" ubuntu@$SERVER_IP"
echo ""
echo "详细调试模式:"
echo "  ssh -vvv -i \"$KEY_FILE\" ubuntu@$SERVER_IP"
echo ""
echo "=========================================="
